### PR TITLE
Change iris dimensions to match the report, and fix encoded polynomial block configurations

### LINKED ISSUE #102: Change iris dimensions to match the production system
Currently we're using iris dimensions of 160x80, but the production dimensions are:
- [x] full resolution: 200 columns by 16x2x2 rows
- [ ] medium resolution: 100 columns by 8x2x2 rows

As part of this change we could also improve performance:
- [x] make sure the polynomial sizes are tight

And ease of use:
- [x] make the polynomial size changes automatic by calculating them from the iris size

This change also needed fixes to the following design issues:
- [x] Split iris bit configurations and encoding configurations
- [x] Avoid confusion between the number of rows in a full iris code, and the number of rows per encoded block

And bugs:
- [x] Calculate polynomial sizes from the encoded size plus padding
- [x] Add missing `impl EncodedConf for MiddleRes`

### PR DESCRIPTION
**Pull request by teor2345**
### Dimension Changes

Currently we're using iris dimensions of 160x80, but the production dimensions are slightly different. So this PR changes those sizes to match the production system.

### Design Changes

As part of this change, we need to fix some design issues:
- [x] Split iris bit configurations and encoding configurations
- [x] Avoid confusion between the number of rows in a full iris code, and the number of rows per encoded block

So this PR creates two different kinds of configs:
- `FullBits`, `MediumBits`, `TinyTest` - the bit sizes and dimensions of the full iris codes and plaintexts
- `FullRes`, `MediumRes`, `TinyTest` - the block sizes and polynomial sizes for encoding (and encryption)

These design changes are needed for ticket #89.

### Cleanups

It also improves performance and ease of use:
- [x] Make polynomial sizes tight, and automatic, by calculating them from the iris size
- [x] Rename config types to be consistent with each other

And fixes some bugs:
- [x] Calculate polynomial sizes from the encoded size plus padding
- [x] Add missing `impl EncodedConf for MiddleRes`
- [x] Add missing tests and benchmarks for `Test*`/`Middle*` (or `Middle*`/`Full*` if `TinyTest` doesn't work)
    - [x] Remove a hard coded `TestRes` in some tests
- [x] Add missing types and inputs/outputs to test failure logs
- [x] Cleanup redundant tests and benchmarks
- [x] Skip a test case that can fail at random with tiny test iris codes

Close #102 
Part of #89, #100

### CODE REVIEW

File: eyelid-match-ops/src/conf.rs [hunk 1]
```diff
@@ -2,43 +2,38 @@
...
+
+/// The polynomial config used in tests.
+///
+/// Temporarily switch to this tiny field to make test errors easier to debug:
+/// ```no_run
+/// RUSTFLAGS="--cfg tiny_poly" cargo test
+/// RUSTFLAGS="--cfg tiny_poly" cargo bench --features benchmark
+/// ```
+#[cfg(tiny_poly)]
+pub type TestBits = TinyTest;
```
Comment (teor2345) [inline eyelid-match-ops/src/conf.rs:39]: This is code movement for consistency.

File: eyelid-match-ops/src/conf.rs [hunk 2]
```diff
@@ -2,43 +2,38 @@
...
+/// Raw full resolution iris code dimensions.
 ///
 /// This uses the full number of iris bits, which gives an upper bound on benchmarks.
-#[derive(Copy, Clone, Debug, Eq, PartialEq)]
-pub struct IrisBits;
-
-/// Full resolution polynomial parameters.
 ///
-/// These are the parameters for full resolution, according to the Inversed Tech report.
+/// TODO: Rename to FullBits
```
Comment (teor2345) [inline eyelid-match-ops/src/conf.rs:9]:
```suggestion
```

File: eyelid-match-ops/src/encoded/conf.rs [hunk 3]
```diff
@@ -4,30 +4,38 @@ use ark_ff::{One, Zero};
...
 
 #[cfg(tiny_poly)]
 use crate::TinyTest;
 
-/// An encoding for an iris code.
+/// The dimensions of an encoding for an iris code, used for efficient matching.
 pub trait EncodeConf {
     /// The configuration of iris code data.
+    ///
+    /// TODO: rename to EyeBits?
```
Comment (teor2345) [inline eyelid-match-ops/src/encoded/conf.rs:17]:
```suggestion
    /// TODO: rename to EyeData and DataConf?
```

File: eyelid-match-ops/src/encoded/conf.rs [hunk 4]
```diff
@@ -59,53 +67,63 @@ pub trait EncodeConf {
...
-
-impl EncodeConf for IrisBits {
-    type EyeConf = IrisBits;
-    type PlainConf = IrisBits;
+impl EncodeConf for FullBits {
+    type EyeConf = FullBits;
+    type PlainConf = FullRes;
 
-    const ROWS_PER_BLOCK: usize = 20;
+    // TODO: using 16 fails with an encryption positive multiplication test error
```
Comment (teor2345) [inline eyelid-match-ops/src/encoded/conf.rs:74]:
```suggestion
```

File: eyelid-match-ops/src/encoded/conf.rs [hunk 5]
```diff
@@ -59,53 +67,63 @@ pub trait EncodeConf {
...
+    const ROWS_PER_BLOCK: usize = 8;
 }
+// As in the report
+const_assert_eq!(
+    <<FullBits as EncodeConf>::PlainConf as PolyConf>::MAX_POLY_DEGREE,
+    2048
+);
```
Comment (teor2345) [inline eyelid-match-ops/src/encoded/conf.rs:80]: @bgillesp full resolution parameters: rows per block, and polynomial degree for full resolution blocks

File: eyelid-match-ops/src/encoded/conf.rs [hunk 6]
```diff
@@ -59,53 +67,63 @@ pub trait EncodeConf {
...
+    const ROWS_PER_BLOCK: usize = 4;
 }
-const_assert!(FullRes::ROWS_PER_BLOCK <= FullRes::COLUMN_LEN);
+// As in the report
 const_assert_eq!(
-    FullRes::NUM_BLOCKS * FullRes::ROWS_PER_BLOCK,
-    FullRes::COLUMN_LEN
+    <<MiddleBits as EncodeConf>::PlainConf as PolyConf>::MAX_POLY_DEGREE,
+    1024
+);
```
Comment (teor2345) [inline eyelid-match-ops/src/encoded/conf.rs:108]: Medium resolution parameters: rows per block, and block polynomial degree

File: eyelid-match-ops/src/iris/conf.rs [hunk 7]
```diff
@@ -69,49 +69,38 @@ pub type IrisCode<const STORE_ELEM_LEN: usize> = BitArray<[IrisStore; STORE_ELEM
...
 pub type IrisMask<const STORE_ELEM_LEN: usize> = BitArray<[IrisStore; STORE_ELEM_LEN]>;
 
-impl IrisConf for IrisBits {
-    const COLUMN_LEN: usize = 80;
-    const COLUMNS: usize = 160;
+impl IrisConf for FullBits {
+    const COLUMNS: usize = 200;
+    const COLUMN_LEN: usize = 16 * 2 * 2;
     const ROTATION_LIMIT: usize = 15;
 }
```
Comment (teor2345) [inline eyelid-match-ops/src/iris/conf.rs:76]: Full resolution iris code dimensions

File: eyelid-match-ops/src/iris/conf.rs [hunk 8]
```diff
@@ -69,49 +69,38 @@ pub type IrisCode<const STORE_ELEM_LEN: usize> = BitArray<[IrisStore; STORE_ELEM
...
-const_assert!(FullRes::MATCH_DENOMINATOR > 0);
-
-impl IrisConf for MiddleRes {
-    const COLUMN_LEN: usize = 5;
-    const COLUMNS: usize = 80;
-    const ROTATION_LIMIT: usize = IrisBits::ROTATION_LIMIT;
+impl IrisConf for MiddleBits {
+    const COLUMNS: usize = 100;
+    const COLUMN_LEN: usize = 8 * 2 * 2;
+    const ROTATION_LIMIT: usize = FullBits::ROTATION_LIMIT;
```
Comment (teor2345) [inline eyelid-match-ops/src/iris/conf.rs:92]: Middle resolution iris code dimensions

File: eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs [hunk 9]
```diff
@@ -42,9 +42,8 @@ pub trait PolyConf: Copy + Clone + Debug + Eq + PartialEq {
     fn coeff_zero() -> &'static Self::Coeff;
 }
 
-impl PolyConf for IrisBits {
-    // This degree requires a larger modulus, Fq79 doesn't work
-    const MAX_POLY_DEGREE: usize = IrisBits::DATA_BIT_LEN.next_power_of_two();
+impl PolyConf for FullRes {
+    const MAX_POLY_DEGREE: usize = FullBits::BLOCK_AND_PADS_BIT_LEN.next_power_of_two();
```
Comment (teor2345) [inline eyelid-match-ops/src/primitives/poly/modular_poly/conf.rs:46]: Polynomial sizes are now calculated automatically, by rounding up the block size to the next power of two.

File: eyelid-match-ops/src/primitives/yashe/conf.rs [hunk 10]
```diff
@@ -296,23 +296,15 @@ where
...
 ///
 /// These are the parameters for full resolution, according to the Inversed Tech report.
 impl YasheConf for FullRes {
     type PolyBN = FullResBN;
 
-    // VERIFY: max T should be 2^15, not 2^11
-    const T: u64 = 2048;
+    // VERIFY: max T should be 2^15, not 2^12
+    // Larger values cause failures in the positive_multiplication_test().
+    const T: u64 = 4096;
```
Comment (teor2345) [inline eyelid-match-ops/src/primitives/yashe/conf.rs:307]: @emmorais happy to revert this change, but it seems to work with the new dimensions.

**Review by teor2345 — COMMENTED** [review]
Things for Bryan and Eduardo to review

**Comment by teor2345** [comment]
Some benchmarks will change because we changed the size of the iris code, for example:

> Benchmark suite	Current: [d38c37e](https://github.com/Inversed-Tech/eyelid/commit/d38c37ebb6f668970d70db550676fe1f3d9fa2a2)	Previous: [b2b5a96](https://github.com/Inversed-Tech/eyelid/commit/b2b5a965c320bd53566e2db63e111063879a68bb)	Ratio
> `Plaintext full match/random`	`657171` ns/iter (`± 56739`)	`975758` ns/iter (`± 7168`)	`0.67`

**Review by emmorais — APPROVED** [review]

**Review by emmorais — APPROVED** [review]

File: eyelid-match-ops/src/iris/conf.rs (hunk 8 above)
Comment (bgillesp) [reply eyelid-match-ops/src/iris/conf.rs:92]: Confirmed that these are the correct dimensions for middle resolution.

File: eyelid-match-ops/src/encoded/conf.rs (hunk 5 above)
Comment (bgillesp) [reply eyelid-match-ops/src/encoded/conf.rs:80]: Confirmed, 8 rows per block for degree 2047 polynomials should be fine for the 200-bit rows with rotation amounts -15 to +15.
